# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md033.md
MD033:
  # Allowed elements
  allowed_elements:
    - table
    - tr
    - td
    - br
    - ul
    - li
    - code
    - a
    - details
    - summary
    - img

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md013.md
MD013:
  # Number of characters
  # we have set this to be very high right now due to the linter not
  # ignoring the limit for inline html and tables
  line_length: 500
